/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaCadastroProfessor;
import br.maua.infrastructure.DAO.AlunoDAO;

import javax.swing.JOptionPane;

/**
 *
 * @author Braia dos Computer
 */
public class TelaCadastroProfessor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCadastroProfessor.class.getName());

    /** Creates new form TelaPerfilAluno */
    public TelaCadastroProfessor() {
        initComponents();
        campoUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        campoSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        campoConfirmarSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelPrincipal = new javax.swing.JPanel();
        painelAzul = new javax.swing.JPanel();
        nomeTitulo = new javax.swing.JLabel();
        CadastroTitulo = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        senhaTitulo = new javax.swing.JLabel();
        ConfirmarSenhaTitulo = new javax.swing.JLabel();
        campoConfirmarSenha = new javax.swing.JTextField();
        entrarBotao = new javax.swing.JButton();
        campoNome = new javax.swing.JTextField();
        campoSobrenome = new javax.swing.JTextField();
        nomeTitulo1 = new javax.swing.JLabel();
        nomeTitulo2 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setBackground(new java.awt.Color(19, 112, 178));
        painelPrincipal.setOpaque(false);
        java.awt.GridBagLayout painelPrincipalLayout = new java.awt.GridBagLayout();
        painelPrincipalLayout.columnWidths = new int[] {0};
        painelPrincipal.setLayout(painelPrincipalLayout);

        painelAzul.setBackground(new java.awt.Color(19, 112, 178));
        painelAzul.setMaximumSize(new java.awt.Dimension(500, 540));
        painelAzul.setMinimumSize(new java.awt.Dimension(500, 500));
        painelAzul.setPreferredSize(new java.awt.Dimension(500, 540));

        nomeTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        nomeTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo.setText("Nome");
        nomeTitulo.setName("nomeTitulo"); // NOI18N

        CadastroTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 60)); // NOI18N
        CadastroTitulo.setForeground(new java.awt.Color(255, 255, 255));
        CadastroTitulo.setText("Cadastro");
        CadastroTitulo.setName("CadastroTitulo"); // NOI18N

        campoUsername.setBackground(new java.awt.Color(204, 204, 204));
        campoUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoUsername.setToolTipText("");
        campoUsername.setBorder(null);
        campoUsername.setMargin(new java.awt.Insets(8, 5, 2, 6));
        campoUsername.setName("campoUsername"); // NOI18N
        campoUsername.addActionListener(this::campoUsernameActionPerformed);

        campoSenha.setBackground(new java.awt.Color(204, 204, 204));
        campoSenha.setBorder(null);
        campoSenha.setName("campoSenha"); // NOI18N
        campoSenha.addActionListener(this::campoSenhaActionPerformed);

        senhaTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        senhaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        senhaTitulo.setText("Senha");
        senhaTitulo.setName("senhaTitulo"); // NOI18N

        ConfirmarSenhaTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        ConfirmarSenhaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmarSenhaTitulo.setText("Confirmar senha");
        ConfirmarSenhaTitulo.setName("ConfirmarSenhaTitulo"); // NOI18N

        campoConfirmarSenha.setBackground(new java.awt.Color(204, 204, 204));
        campoConfirmarSenha.setBorder(null);
        campoConfirmarSenha.setName("campoConfirmarSenha"); // NOI18N
        campoConfirmarSenha.addActionListener(this::campoConfirmarSenhaActionPerformed);

        entrarBotao.setBackground(new java.awt.Color(240, 147, 32));
        entrarBotao.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        entrarBotao.setForeground(new java.awt.Color(255, 255, 255));
        entrarBotao.setText("Entrar");
        entrarBotao.setBorder(null);
        entrarBotao.setName("entrarBotao"); // NOI18N
        entrarBotao.addActionListener(this::entrarBotaoActionPerformed);

        campoNome.setBackground(new java.awt.Color(204, 204, 204));
        campoNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoNome.setToolTipText("");
        campoNome.setBorder(null);
        campoNome.setMargin(new java.awt.Insets(8, 5, 2, 6));
        campoNome.setName("campoNome"); // NOI18N
        campoNome.addActionListener(this::campoNomeActionPerformed);

        campoSobrenome.setBackground(new java.awt.Color(204, 204, 204));
        campoSobrenome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoSobrenome.setToolTipText("");
        campoSobrenome.setBorder(null);
        campoSobrenome.setMargin(new java.awt.Insets(8, 5, 2, 6));
        campoSobrenome.setName("campoNome"); // NOI18N
        campoSobrenome.addActionListener(this::campoSobrenomeActionPerformed);

        nomeTitulo1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        nomeTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo1.setText("Username");
        nomeTitulo1.setName("nomeTitulo"); // NOI18N

        nomeTitulo2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        nomeTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo2.setText("Sobrenome");
        nomeTitulo2.setName("nomeTitulo"); // NOI18N

        javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
        painelAzul.setLayout(painelAzulLayout);
        painelAzulLayout.setHorizontalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAzulLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(entrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmarSenhaTitulo)
                            .addComponent(campoConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaTitulo)
                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTitulo)
                            .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTitulo1)
                            .addComponent(nomeTitulo2)))
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(CadastroTitulo)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        painelAzulLayout.setVerticalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CadastroTitulo)
                .addGap(18, 18, 18)
                .addComponent(nomeTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nomeTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(senhaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmarSenhaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(entrarBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        nomeTitulo.getAccessibleContext().setAccessibleName("nomeTitulo");
        CadastroTitulo.getAccessibleContext().setAccessibleName("CadastroTitulo");
        campoUsername.getAccessibleContext().setAccessibleName("campoNome");
        campoSenha.getAccessibleContext().setAccessibleName("campoSenha");
        senhaTitulo.getAccessibleContext().setAccessibleName("senhaTitulo");
        ConfirmarSenhaTitulo.getAccessibleContext().setAccessibleName("ConfirmarSenhaTitulo");
        campoConfirmarSenha.getAccessibleContext().setAccessibleName("campoConfirmarSenha");
        entrarBotao.getAccessibleContext().setAccessibleName("entrarBotao");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        painelPrincipal.add(painelAzul, gridBagConstraints);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 5.png"))); // NOI18N
        imagemFundo.setAlignmentY(0.0F);
        imagemFundo.setIconTextGap(0);
        imagemFundo.setMaximumSize(new java.awt.Dimension(24000, 24000));
        imagemFundo.setMinimumSize(new java.awt.Dimension(1024, 768));
        imagemFundo.setName("imagemFundo"); // NOI18N
        imagemFundo.setPreferredSize(new java.awt.Dimension(1024, 768));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        painelPrincipal.add(imagemFundo, gridBagConstraints);
        imagemFundo.getAccessibleContext().setAccessibleName("imagemFundo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsernameActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void campoConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoConfirmarSenhaActionPerformed

    private void entrarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotaoActionPerformed
        // TODO add your handling code here:
        
        String nome = campoNome.getText();
        String sobrenome = campoSobrenome.getText();
        String username = campoUsername.getText();
        String senha = campoSenha.getText();
        String senhaConfirmacao = campoConfirmarSenha.getText();

        if (nome.isEmpty() || senha.isEmpty() || senhaConfirmacao.isEmpty()|| username.isEmpty() || sobrenome.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Preencha todos os campos!", 
                "Aviso", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!senha.equals(senhaConfirmacao)) {
            JOptionPane.showMessageDialog(this,
                "As senhas não coincidem! Digite novamente.", 
                "Erro de Senha", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            
            br.maua.domain.Professor novoProfessor = new br.maua.domain.Professor(nome, sobrenome, username, senha);

            br.maua.infrastructure.ProfessorDAO dao = new br.maua.infrastructure.ProfessorDAO();
            dao.salvarNoBanco(novoProfessor);
            
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            
           
            new br.maua.presentation.TelaLogin.TelaLogin().setVisible(true);
            this.dispose();
            
        } catch (java.sql.SQLException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,
                "Erro ao salvar no banco de dados: " + ex.getMessage(),
                "Erro de Banco",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarBotaoActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSobrenomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroProfessor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroTitulo;
    private javax.swing.JLabel ConfirmarSenhaTitulo;
    private javax.swing.JTextField campoConfirmarSenha;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoSobrenome;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JButton entrarBotao;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel nomeTitulo;
    private javax.swing.JLabel nomeTitulo1;
    private javax.swing.JLabel nomeTitulo2;
    private javax.swing.JPanel painelAzul;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JLabel senhaTitulo;
    // End of variables declaration//GEN-END:variables

}
