/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaCriarTarefa;

import br.maua.domain.*;
import br.maua.infrastructure.DAO.CasaDAO;
import br.maua.infrastructure.DAO.TarefaDAO;
import br.maua.presentation.TelaCriarTarefa.Components.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.logging.Logger;

/**
 *
 * @author Lenovo
 */
public class TelaCriarTarefa extends JFrame{
    
    private static final Logger logger = Logger.getLogger(TelaCriarTarefa.class.getName());
    private final JFrame telaAnterior;
    private final Tarefa tarefa;
    private final Map<JPanel, QuestaoUI> questoesUI = new HashMap<>();
    /**
     * Creates new form TelaCriarTarefa2
     */
    public TelaCriarTarefa(JFrame telaAnterior) throws SQLException {
        this.telaAnterior = telaAnterior;
        this.tarefa = new Tarefa();
        initComponents();
        carregarCasas();

        painelConteudo.removeAll();
        painelConteudo.add(criarBarraTopo());
        painelConteudo.add(Box.createVerticalStrut(5));

        painelConteudo.add(jPanel1); 
        
        painelConteudo.add(jPanel2);
        painelConteudo.add(Box.createVerticalStrut(20));
        
        painelConteudo.add(jPanel3); 
        painelConteudo.add(Box.createVerticalStrut(20));
        
        
        
        painelConteudo.add(jPanel15); // Botão "+ Adicionar Questão"
        painelConteudo.add(Box.createVerticalStrut(40));

        jButton1.setAlignmentX(Component.CENTER_ALIGNMENT);
        painelConteudo.add(jButton1); // Botão "Salvar Tarefa" dentro da área rolável
        painelConteudo.add(Box.createVerticalStrut(40));

        
        painelConteudo.revalidate();
        painelConteudo.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        painelConteudo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new JPanel();
        jLabel3 = new JLabel();
        txtTitulo = new JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(e -> salvarTarefa());


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                telaAnterior.setVisible(true);
            }
        });

        txtTitulo.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { atualizar(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { atualizar(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { atualizar(); }

            private void atualizar() {
                tarefa.setTitulo(txtTitulo.getText());
            }
        });


        painelConteudo.setBackground(new java.awt.Color(255, 255, 255));
        painelConteudo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 112, 178), 30));
        painelConteudo.setMaximumSize(new java.awt.Dimension(32827, 32827));
        painelConteudo.setLayout(new javax.swing.BoxLayout(painelConteudo, javax.swing.BoxLayout.Y_AXIS));



        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        painelConteudo.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(19, 112, 178));
        jPanel2.setMaximumSize(new java.awt.Dimension(592, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Novo Questionário");

        jPanel7.setBackground(new Color(19, 112, 178));

        jLabel3.setText("Título:");
        jLabel3.setForeground(new Color(255, 255, 255));
        txtTitulo.setPreferredSize(new Dimension(580, 32));
        txtTitulo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 32));
        GroupLayout jPanel7Layout = new GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);

        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        painelConteudo.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(19, 112, 178));
        jPanel3.setMaximumSize(new java.awt.Dimension(630, 200));
        jComboBox2.setModel(new DefaultComboBoxModel<>(new Casa[]{new Casa("Carregando...")}));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox2, 0, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                String texto = jFormattedTextField1.getText();

                try {
                    java.time.format.DateTimeFormatter entrada = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    java.time.format.DateTimeFormatter saida = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");

                    java.time.LocalDate data = java.time.LocalDate.parse(texto, entrada);

                    tarefa.setPrazo(data.format(saida));

                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Data inválida! Use dd/MM/yyyy");
                    jFormattedTextField1.setText("");
                }
            }
        });
        jLabel2.setText("Prazo:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(jPanel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            )

        );

        painelConteudo.add(jPanel3);

        jPanel15.setBackground(new java.awt.Color(19, 112, 178));
        jPanel15.setMaximumSize(new java.awt.Dimension(400, 68));
        jPanel15.setPreferredSize(new java.awt.Dimension(600, 222));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel15MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("+ Adicionar Questão");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel6)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        painelConteudo.add(jPanel15);

        jButton1.setBackground(new java.awt.Color(240, 147, 32));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salvar Tarefa");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 35));
        painelConteudo.add(jButton1);

        jScrollPane1.setViewportView(painelConteudo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        tarefa.setCasa( (Casa)jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ActionPerformed


    private void jPanel15MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseClicked
    int numeroQuestao = 1;
    for (Component c : painelConteudo.getComponents()) {
        if (c instanceof JPanel && c != jPanel1 && c != jPanel2 && c != jPanel3 && c != jPanel15) {
            numeroQuestao++;
        }
    }

    JPanel novaQuestaoCompleta = criarPainelNovaQuestao(numeroQuestao);
    jPanel15.setAlignmentX(Component.CENTER_ALIGNMENT);
    painelConteudo.remove(jPanel15);
    painelConteudo.remove(jButton1);

    painelConteudo.add(Box.createVerticalStrut(10));
    painelConteudo.add(novaQuestaoCompleta);

    
    painelConteudo.add(Box.createVerticalStrut(10));
    painelConteudo.add(jPanel15);
    painelConteudo.add(Box.createVerticalStrut(10));
    painelConteudo.add(jButton1);
    painelConteudo.add(Box.createVerticalStrut(20));

    painelConteudo.revalidate();
    painelConteudo.repaint();
    
    SwingUtilities.invokeLater(() -> {
        jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
    });
    }//GEN-LAST:event_jPanel15MouseClicked
    
    private JPanel criarPainelNovaQuestao(int numero) {
        JPanel painelQuestao = new JPanel();
        painelQuestao.setBackground(new Color(240, 147, 32));
        painelQuestao.setLayout(new BoxLayout(painelQuestao, BoxLayout.Y_AXIS));
        painelQuestao.setBorder(BorderFactory.createEmptyBorder(14, 20, 14, 20));
        
        painelQuestao.setAlignmentX(Component.CENTER_ALIGNMENT);
        painelQuestao.setMaximumSize(new Dimension(632, 340));
        painelQuestao.setPreferredSize(new Dimension(632, 340));

        JLabel lblTitulo = new JLabel("Questão - " + numero);
        lblTitulo.setFont(new Font("Segoe UI", 1, 18));
        lblTitulo.setForeground(new Color(255, 255, 255));
        lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        painelQuestao.add(lblTitulo);
        painelQuestao.add(Box.createVerticalStrut(10));

        JComboBox<String> comboTipo = new JComboBox<>(new String[] { "Múltipla Escolha", "Dissertativa", "Upload" });
        comboTipo.setMaximumSize(new Dimension(580, 35));
        comboTipo.setPreferredSize(new Dimension(580, 35));
        comboTipo.setAlignmentX(Component.LEFT_ALIGNMENT);
        painelQuestao.add(comboTipo);
        painelQuestao.add(Box.createVerticalStrut(8));

        JTextArea txtEnunciado = new JTextArea(4, 20);
        txtEnunciado.setText("Digite o enunciado da questão aqui...");
        txtEnunciado.setFont(new Font("Segoe UI", 0, 14));
        txtEnunciado.setLineWrap(true);
        txtEnunciado.setWrapStyleWord(true);

        JScrollPane scrollEnunciado = new JScrollPane(txtEnunciado);
        scrollEnunciado.setMaximumSize(new Dimension(580, 80));
        scrollEnunciado.setPreferredSize(new Dimension(580, 80));
        scrollEnunciado.setAlignmentX(Component.LEFT_ALIGNMENT);
        painelQuestao.add(scrollEnunciado);
        painelQuestao.add(Box.createVerticalStrut(8));

        JPanel painelDinamico = new JPanel();
        painelDinamico.setBackground(new Color(240, 147, 32));
        painelDinamico.setLayout(new BoxLayout(painelDinamico, BoxLayout.Y_AXIS));
        painelDinamico.setAlignmentX(Component.LEFT_ALIGNMENT);
        painelQuestao.add(painelDinamico);

        Runnable atualizarCampos = () -> {
            painelDinamico.removeAll();
            String tipo = (String) comboTipo.getSelectedItem();

            if ("Múltipla Escolha".equals(tipo)) {
                QuestaoAlternativaUI qalternativa = new QuestaoAlternativaUI();
                qalternativa.enunciado = txtEnunciado;
                questoesUI.put(painelQuestao, qalternativa);
                ButtonGroup grupoRadio = new ButtonGroup();
                JPanel painelAlternativas = new JPanel();
                painelAlternativas.setBackground(new Color(240, 147, 32));
                painelAlternativas.setLayout(new BoxLayout(painelAlternativas, BoxLayout.Y_AXIS));
                painelAlternativas.setAlignmentX(Component.LEFT_ALIGNMENT);

                BiConsumer<JPanel, ButtonGroup> adicionarAlternativa = (painel, grupo) -> {
                    AlternativaUI alternativa = new AlternativaUI();
                    qalternativa.addAlternativa(alternativa);
                    JPanel linhaAlternativa = new JPanel();
                    linhaAlternativa.setBackground(new Color(240, 147, 32));
                    linhaAlternativa.setLayout(new BoxLayout(linhaAlternativa, BoxLayout.X_AXIS));
                    linhaAlternativa.setAlignmentX(Component.LEFT_ALIGNMENT);

                    alternativa.radio = new JRadioButton();
                    alternativa.radio.setBackground(new Color(240, 147, 32));
                    grupo.add(alternativa.radio);

                    alternativa.campo = new JTextField("Digite a alternativa");
                    alternativa.campo.setMaximumSize(new Dimension(500, 32));
                    alternativa.campo.setPreferredSize(new Dimension(500, 32));

                    linhaAlternativa.add(alternativa.radio);
                    linhaAlternativa.add(Box.createHorizontalStrut(8));
                    linhaAlternativa.add(alternativa.campo);
                    painel.add(linhaAlternativa);
                    painel.add(Box.createVerticalStrut(8));
                };

                for (int i = 0; i < 4; i++) {
                    adicionarAlternativa.accept(painelAlternativas, grupoRadio);
                }

                JButton btnAdicionarAlternativa = new JButton("Adicionar alternativa");
                btnAdicionarAlternativa.setAlignmentX(Component.LEFT_ALIGNMENT);
                btnAdicionarAlternativa.addActionListener(evt -> {
                    adicionarAlternativa.accept(painelAlternativas, grupoRadio);
                    painelAlternativas.revalidate();
                    painelAlternativas.repaint();
                    painelQuestao.revalidate();
                    painelQuestao.repaint();
                });

                painelDinamico.add(painelAlternativas);
                painelDinamico.add(Box.createVerticalStrut(6));
                painelDinamico.add(btnAdicionarAlternativa);
                painelQuestao.setMaximumSize(new Dimension(632, 460));
                painelQuestao.setPreferredSize(new Dimension(632, 460));
                
            } else if ("Upload".equals(tipo)) {
                QuestaoUploadUI upload = new QuestaoUploadUI();
                upload.enunciado =  txtEnunciado;
                JLabel lblTituloArquivo = new JLabel("Título do arquivo:");
                lblTituloArquivo.setFont(new Font("Segoe UI", 0, 14));
                lblTituloArquivo.setForeground(new Color(255, 255, 255));
                lblTituloArquivo.setAlignmentX(Component.LEFT_ALIGNMENT);
                painelDinamico.add(lblTituloArquivo);
                painelDinamico.add(Box.createVerticalStrut(5));

                upload.titulo = new JTextField();
                upload.titulo.setMaximumSize(new Dimension(580, 32));
                upload.titulo.setPreferredSize(new Dimension(580, 32));
                upload.titulo.setAlignmentX(Component.LEFT_ALIGNMENT);
                painelDinamico.add(upload.titulo);

                painelDinamico.add(Box.createVerticalStrut(10));
                JLabel lblArquivo = new JLabel("Arquivo:");
                lblArquivo.setFont(new Font("Segoe UI", 0, 14));
                lblArquivo.setForeground(new Color(255, 255, 255));
                lblArquivo.setAlignmentX(Component.LEFT_ALIGNMENT);
                painelDinamico.add(lblArquivo);
                painelDinamico.add(Box.createVerticalStrut(5));

                JPanel linhaArquivo = new JPanel();
                linhaArquivo.setBackground(new Color(240, 147, 32));
                linhaArquivo.setLayout(new BoxLayout(linhaArquivo, BoxLayout.X_AXIS));
                linhaArquivo.setAlignmentX(Component.LEFT_ALIGNMENT);

                JTextField campoArquivo = new JTextField("Selecione o arquivo da tarefa");
                campoArquivo.setEditable(false);
                campoArquivo.setMaximumSize(new Dimension(430, 32));
                campoArquivo.setPreferredSize(new Dimension(430, 32));

                JButton btnSelecionarArquivo = new JButton("Escolher arquivo");
                btnSelecionarArquivo.addActionListener(evt -> {
                    JFileChooser chooser = new JFileChooser();
                    int resultado = chooser.showOpenDialog(painelQuestao);
                    if (resultado == JFileChooser.APPROVE_OPTION) {
                        File arquivo = chooser.getSelectedFile();
                        campoArquivo.setText(arquivo.getName());
                        upload.arquivo = arquivo;
                    }
                });

                linhaArquivo.add(campoArquivo);
                linhaArquivo.add(Box.createHorizontalStrut(8));
                linhaArquivo.add(btnSelecionarArquivo);

                painelDinamico.add(linhaArquivo);
                painelQuestao.setMaximumSize(new Dimension(632, 360));
                painelQuestao.setPreferredSize(new Dimension(632, 360));
                questoesUI.put(painelQuestao, upload);
            } else {
                QuestaoDissertativaUI dissertativa = new QuestaoDissertativaUI();
                dissertativa.enunciado = txtEnunciado;
                JLabel lblResposta = new JLabel("Resposta Modelo:");
                lblResposta.setFont(new Font("Segoe UI", 0, 14));
                lblResposta.setForeground(new Color(255, 255, 255));
                lblResposta.setAlignmentX(Component.LEFT_ALIGNMENT);
                painelDinamico.add(lblResposta);
                painelDinamico.add(Box.createVerticalStrut(5));

                dissertativa.resposta = new JTextArea(3, 20);
                dissertativa.resposta.setEditable(true);
                JScrollPane scrollResposta = new JScrollPane(dissertativa.resposta);
                scrollResposta.setMaximumSize(new Dimension(580, 60));
                scrollResposta.setPreferredSize(new Dimension(580, 60));
                scrollResposta.setAlignmentX(Component.LEFT_ALIGNMENT);

                painelDinamico.add(scrollResposta);
                painelQuestao.setMaximumSize(new Dimension(632, 300));
                painelQuestao.setPreferredSize(new Dimension(632, 300));
                questoesUI.put(painelQuestao, dissertativa);
            }

            painelQuestao.revalidate();
            painelQuestao.repaint();
        };

        comboTipo.addActionListener(e -> atualizarCampos.run());

        atualizarCampos.run();
        return painelQuestao;
}

    private void salvarTarefa(){
        tarefa.setTitulo(txtTitulo.getText());
        for(QuestaoUI q : questoesUI.values()){
            q.salvar(tarefa);
        }
        try{
        TarefaDAO.commitTarefa(tarefa);
        JOptionPane.showMessageDialog(null, "Tarefa gerada com sucesso!", "Tarefa", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        telaAnterior.setVisible(true);
    } catch(SQLException e){
            tarefa.getQuestoes().clear();
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao Salvar Questao", JOptionPane.ERROR_MESSAGE);
        }
    }

    private JPanel criarBarraTopo() {
        barraTopo = new JPanel();
        barraTopo.setLayout(new BorderLayout());
        barraTopo.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        barraTopo.setBackground(Color.WHITE);

        btnVoltar = new JButton("← Voltar");
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setFocusPainted(false);
        btnVoltar.setFont(new Font("Segoe UI", Font.BOLD, 14));

        btnVoltar.addActionListener(e -> {
            dispose();
            telaAnterior.setVisible(true);
        });

        barraTopo.add(btnVoltar, BorderLayout.WEST);

        return barraTopo;
    }

    private void carregarCasas() {
        DefaultComboBoxModel<Casa> model = new DefaultComboBoxModel<>();
        try {
            List<Casa> casas = CasaDAO.listarCasas();
            for (Casa c : casas) {
                model.addElement(c);
            }
            jComboBox2.setModel(model);
        } catch (SQLException ex) {
            jComboBox2.setModel(new DefaultComboBoxModel<>());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro ao Carregar Casas", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<Casa> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel barraTopo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel painelConteudo;
    // End of variables declaration//GEN-END:variables


}
