/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaModalPerfilAluno;

import java.sql.SQLException;
import java.util.Map;

import javax.swing.JOptionPane;

import br.maua.domain.Aluno;
import br.maua.infrastructure.DAO.AlunoDAO;
import br.maua.presentation.TelaNotaAluno.TelaNotaAluno;

/**
 *
 * @author Luiza
 */
public class ModalPerfilAluno extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ModalPerfilAluno.class.getName());
    private final Aluno aluno;

    /** Creates new form TelaPerfilAluno */
    public ModalPerfilAluno(Aluno aluno) {
        this.aluno = aluno;
        initComponents();
        obterProgresso();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        if (this.aluno != null) {
            nomeAluno.setText(aluno.getNome());
            raAluno.setText(aluno.getUsername());
            cursoAluno.setText(aluno.getTurma().getCurso().toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        painelAzul = new javax.swing.JPanel();
        painelCinza = new javax.swing.JPanel();
        nomeAluno = new java.awt.Label();
        cursoAluno = new javax.swing.JLabel();
        raAluno = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        btnNotas = new javax.swing.JButton();
        atividadesConcluidas = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAzul.setBackground(new java.awt.Color(19, 112, 178));

        painelCinza.setBackground(new java.awt.Color(217, 217, 217));

        nomeAluno.setAlignment(java.awt.Label.CENTER);
        nomeAluno.setBackground(new java.awt.Color(240, 147, 32));
        nomeAluno.setFont(new java.awt.Font("STXihei", 0, 48)); // NOI18N
        nomeAluno.setForeground(new java.awt.Color(255, 255, 255));
        nomeAluno.setText("nomeAluno");

        cursoAluno.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        cursoAluno.setForeground(new java.awt.Color(255, 255, 255));
        cursoAluno.setText("Curso do Aluno");

        raAluno.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        raAluno.setForeground(new java.awt.Color(255, 255, 255));
        raAluno.setText("12-34567.8");

        javax.swing.GroupLayout painelCinzaLayout = new javax.swing.GroupLayout(painelCinza);
        painelCinza.setLayout(painelCinzaLayout);
        painelCinzaLayout.setHorizontalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(raAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cursoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(216, 216, 216))
        );
        painelCinzaLayout.setVerticalGroup(
            painelCinzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cursoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(raAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        progresso.setForeground(new java.awt.Color(240, 147, 32));
        progresso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        btnNotas.setBackground(new java.awt.Color(240, 147, 32));
        btnNotas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnNotas.setForeground(new java.awt.Color(255, 255, 255));
        btnNotas.setText("Notas");
        btnNotas.setBorder(null);
        btnNotas.setBorderPainted(false);
        btnNotas.setFocusPainted(false);
        btnNotas.setRequestFocusEnabled(false);
        btnNotas.setRolloverEnabled(false);
        btnNotas.addActionListener(this::btnNotasActionPerformed);

        atividadesConcluidas.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        atividadesConcluidas.setForeground(new java.awt.Color(255, 255, 255));
        atividadesConcluidas.setText("Atividades Concluídas: xx/xx");

        btnLogout.setBackground(new java.awt.Color(208, 204, 193));
        btnLogout.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogout.setBorderPainted(false);
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        jButton1.setBackground(new java.awt.Color(240, 147, 32));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
        painelAzul.setLayout(painelAzulLayout);
        painelAzulLayout.setHorizontalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(atividadesConcluidas, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(progresso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        painelAzulLayout.setVerticalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progresso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(atividadesConcluidas)
                .addGap(18, 18, 18)
                .addComponent(btnNotas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void obterProgresso() {
        try {
            Map<String, Integer> progresso = AlunoDAO.obterProgressoAluno(this.aluno);
            int tarefasConcluidas = progresso.get("tarefasConcluidas");
            int totalTarefas = progresso.get("totalTarefas");
            int porcentagemProgresso = progresso.get("porcentagemProgresso");
            atividadesConcluidas.setText(String.format("Atividades Concluídas: %d/%d", tarefasConcluidas, totalTarefas));
            this.progresso.setMinimum(0);
            this.progresso.setMaximum(100);
            this.progresso.setValue(porcentagemProgresso);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao obter progresso de aluno: " + e.getMessage());
            e.printStackTrace();
        }
    }
    private void btnNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotasActionPerformed
        if (aluno == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Aluno não carregado.");
            return;
        }

        br.maua.presentation.TelaNavegacao.abrir(this, new TelaNotaAluno(aluno, this));
    }//GEN-LAST:event_btnNotasActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new br.maua.presentation.TelaLogin.TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new br.maua.presentation.TelaTabuleiro.TelaTabuleiro1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atividadesConcluidas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNotas;
    private javax.swing.JLabel cursoAluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private java.awt.Label nomeAluno;
    private javax.swing.JPanel painelAzul;
    private javax.swing.JPanel painelCinza;
    private javax.swing.JProgressBar progresso;
    private javax.swing.JLabel raAluno;
    // End of variables declaration//GEN-END:variables

}
