/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.maua.presentation.TelaQuestionarioAluno;

import br.maua.domain.Questao;
import br.maua.domain.QuestaoAlternativa;
import br.maua.domain.RespostaAlternativa;
import br.maua.domain.Alternativa;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JRadioButton;
import java.util.HashMap;
import java.util.Map;
/**
 *
 * @author Luiza
 */
public class PainelQuestaoAlternativa extends javax.swing.JPanel {

    private ButtonGroup grupo = new ButtonGroup();
    private Map<JRadioButton, Alternativa> alternativasMap =
        new HashMap<>();
    /**
     * Creates new form PainelQuestaoAlternativa
     */
    public PainelQuestaoAlternativa(QuestaoAlternativa questao) {
        initComponents();
        jTextPane2.setEditable(false);
        jTextPane2.setFocusable(false);
        jTextPane2.setText(
        questao.getEnunciado()
        );
        PainelOpcoesAlternativas.setLayout(
                new BoxLayout(
                    PainelOpcoesAlternativas, 
                        BoxLayout.Y_AXIS
                )
        );
        for (Alternativa alt :
            questao.getAlternativas()) {

        JRadioButton radio =
                 criarRadioButton(
                        alt.getEnunciado()
                );

        grupo.add(radio);
        PainelOpcoesAlternativas.add(radio);
        alternativasMap.put(radio, alt);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAlternativa = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        PainelOpcoesAlternativas = new javax.swing.JPanel();

        PainelAlternativa.setBackground(new java.awt.Color(217, 217, 217));

        jTextPane2.setEditable(false);
        jTextPane2.setBackground(new java.awt.Color(19, 112, 178));
        jTextPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(jTextPane2);

        PainelOpcoesAlternativas.setBackground(new java.awt.Color(240, 147, 32));

        javax.swing.GroupLayout PainelOpcoesAlternativasLayout = new javax.swing.GroupLayout(PainelOpcoesAlternativas);
        PainelOpcoesAlternativas.setLayout(PainelOpcoesAlternativasLayout);
        PainelOpcoesAlternativasLayout.setHorizontalGroup(
            PainelOpcoesAlternativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        PainelOpcoesAlternativasLayout.setVerticalGroup(
            PainelOpcoesAlternativasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PainelAlternativaLayout = new javax.swing.GroupLayout(PainelAlternativa);
        PainelAlternativa.setLayout(PainelAlternativaLayout);
        PainelAlternativaLayout.setHorizontalGroup(
            PainelAlternativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(PainelOpcoesAlternativas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelAlternativaLayout.setVerticalGroup(
            PainelAlternativaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAlternativaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(PainelOpcoesAlternativas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelAlternativa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelAlternativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private JRadioButton criarRadioButton(
        String texto) {

    JRadioButton radio =
            new JRadioButton(texto);

    radio.setBackground(
            new java.awt.Color(240,147,32));

    radio.setForeground(
            java.awt.Color.WHITE);

    radio.setFont(
            new java.awt.Font(
                    "Segoe UI",
                    java.awt.Font.PLAIN,
                    12));

    return radio;
}
    public int getAlternativaSelecionada() {

    for (JRadioButton radio :
            alternativasMap.keySet()) {

        if (radio.isSelected()) {

            return alternativasMap
                    .get(radio)
                    .getIdAlternativa();    
        }
    }

    return -1;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAlternativa;
    private javax.swing.JPanel PainelOpcoesAlternativas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
