/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.maua.presentation.TelaQuestionarioAluno;

import java.io.File;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import br.maua.domain.QuestaoUpload;

/**
 *
 * @author Luiza
 */
public class PainelQuestaoUpload extends javax.swing.JPanel {
    private File arquivoSelecionado;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaQuestionarioAluno.class.getName());
    /**
     * Creates new form PainelQuestaoUpload
     */
    public PainelQuestaoUpload(QuestaoUpload questao) {
        initComponents();
        jTextPane4.setEditable(false);
        jTextPane4.setFocusable(false);
        jTextPane4.setText(
        questao.getEnunciado()
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelUpload = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        btnDownload = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();

        PainelUpload.setBackground(new java.awt.Color(217, 217, 217));

        jTextPane4.setEditable(false);
        jTextPane4.setBackground(new java.awt.Color(19, 112, 178));
        jTextPane4.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jTextPane4);

        btnDownload.setBackground(new java.awt.Color(19, 112, 178));
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setText("Download do arquivo");
        btnDownload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDownload.addActionListener(this::btnDownloadActionPerformed);

        btnUpload.setBackground(new java.awt.Color(240, 147, 32));
        btnUpload.setForeground(new java.awt.Color(255, 255, 255));
        btnUpload.setText("Upload de arquivo");
        btnUpload.addActionListener(this::btnUploadActionPerformed);

        javax.swing.GroupLayout PainelUploadLayout = new javax.swing.GroupLayout(PainelUpload);
        PainelUpload.setLayout(PainelUploadLayout);
        PainelUploadLayout.setHorizontalGroup(
            PainelUploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addComponent(btnDownload, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
            .addComponent(btnUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelUploadLayout.setVerticalGroup(
            PainelUploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelUploadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelUpload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        try {
            String arquivoPath = "/assets/";
            String arquivo = "a.pdf";
            arquivoPath = arquivoPath + arquivo;

            InputStream inputStream = getClass().getResourceAsStream(arquivoPath);

            if (inputStream == null) {
                JOptionPane.showMessageDialog(this,
                    "Arquivo não encontrado em: " + arquivoPath);
                return;
            }

            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Salvar arquivo");
            chooser.setSelectedFile(new File("a.pdf"));

            int opcao = chooser.showSaveDialog(this);

            if (opcao == JFileChooser.APPROVE_OPTION) {
                File destino = chooser.getSelectedFile();

                // Copia do InputStream para o destino
                Files.copy(inputStream, destino.toPath(),
                    StandardCopyOption.REPLACE_EXISTING);

                JOptionPane.showMessageDialog(this, "Download concluído!");
            }

            inputStream.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            arquivoSelecionado = fileChooser.getSelectedFile();
            System.out.println("Arquivo selecionado: " + arquivoSelecionado.getAbsolutePath());
        }
    }//GEN-LAST:event_btnUploadActionPerformed
    public File getArquivoSelecionado() {
        return arquivoSelecionado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelUpload;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnUpload;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
