/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaLogin;

import br.maua.infrastructure.DAO.AlunoDAO;
import br.maua.infrastructure.ProfessorDAO;

/**
 *
 * @author Lenovo
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        painelAzul = new javax.swing.JPanel();
        nomeTitulo10 = new javax.swing.JLabel();
        CadastroTitulo5 = new javax.swing.JLabel();
        campoUsername = new javax.swing.JTextField();
        campoSenha = new javax.swing.JTextField();
        senhaTitulo = new javax.swing.JLabel();
        entrarBotao10 = new javax.swing.JButton();
        entrarBotao11 = new javax.swing.JButton();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        painelAzul.setBackground(new java.awt.Color(19, 112, 178));
        painelAzul.setMaximumSize(new java.awt.Dimension(500, 500));
        painelAzul.setMinimumSize(new java.awt.Dimension(500, 500));
        painelAzul.setPreferredSize(new java.awt.Dimension(500, 500));

        nomeTitulo10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        nomeTitulo10.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo10.setText("Username");
        nomeTitulo10.setName("nomeTitulo"); // NOI18N

        CadastroTitulo5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 60)); // NOI18N
        CadastroTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        CadastroTitulo5.setText("Login");
        CadastroTitulo5.setName("CadastroTitulo"); // NOI18N

        campoUsername.setBackground(new java.awt.Color(204, 204, 204));
        campoUsername.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoUsername.setToolTipText("");
        campoUsername.setBorder(null);
        campoUsername.setMargin(new java.awt.Insets(8, 5, 2, 6));
        campoUsername.setName("campoNome"); // NOI18N
        campoUsername.addActionListener(this::campoUsernameActionPerformed);

        campoSenha.setBackground(new java.awt.Color(204, 204, 204));
        campoSenha.setBorder(null);
        campoSenha.setName("campoSenha"); // NOI18N
        campoSenha.addActionListener(this::campoSenhaActionPerformed);

        senhaTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        senhaTitulo.setForeground(new java.awt.Color(255, 255, 255));
        senhaTitulo.setText("Senha");
        senhaTitulo.setName("senhaTitulo"); // NOI18N

        entrarBotao10.setBackground(new java.awt.Color(240, 147, 32));
        entrarBotao10.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        entrarBotao10.setForeground(new java.awt.Color(255, 255, 255));
        entrarBotao10.setText("Entrar");
        entrarBotao10.setBorder(null);
        entrarBotao10.setName("entrarBotao"); // NOI18N
        entrarBotao10.addActionListener(this::entrarBotao10ActionPerformed);

        entrarBotao11.setBackground(new java.awt.Color(240, 147, 32));
        entrarBotao11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        entrarBotao11.setForeground(new java.awt.Color(255, 255, 255));
        entrarBotao11.setText("Primeiro acesso? Clique aqui");
        entrarBotao11.setBorder(null);
        entrarBotao11.setName("entrarBotao"); // NOI18N
        entrarBotao11.addActionListener(this::entrarBotao11ActionPerformed);

        javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
        painelAzul.setLayout(painelAzulLayout);
        painelAzulLayout.setHorizontalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaTitulo)
                            .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTitulo10)
                            .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(entrarBotao10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(entrarBotao11, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAzulLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(CadastroTitulo5)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        painelAzulLayout.setVerticalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(CadastroTitulo5)
                .addGap(28, 28, 28)
                .addComponent(nomeTitulo10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(entrarBotao10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(entrarBotao11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel1.add(painelAzul, gridBagConstraints);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 5.png"))); // NOI18N
        imagemFundo.setAlignmentY(0.0F);
        imagemFundo.setIconTextGap(0);
        imagemFundo.setMaximumSize(new java.awt.Dimension(24000, 24000));
        imagemFundo.setMinimumSize(new java.awt.Dimension(1024, 768));
        imagemFundo.setName("imagemFundo"); // NOI18N
        imagemFundo.setPreferredSize(new java.awt.Dimension(1024, 768));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(imagemFundo, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUsernameActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void entrarBotao10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotao10ActionPerformed
        // TODO add your handling code here:
        String usuarioDigitado = campoUsername.getText().trim();
        String senhaDigitada = campoSenha.getText();

        if (usuarioDigitado.isEmpty() || senhaDigitada.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor, preencha o Nome e a Senha para entrar!",
                "Campos Vazios",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            br.maua.infrastructure.AlunoDAO alunoDAO = new br.maua.infrastructure.AlunoDAO();
            br.maua.infrastructure.ProfessorDAO professorDAO = new br.maua.infrastructure.ProfessorDAO();
            boolean usuarioValido = alunoDAO.autenticar(usuarioDigitado, senhaDigitada);

            if (usuarioValido) {
                javax.swing.JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");
                
                String tipo_usuario = alunoDAO.obterTipoUsuario(usuarioDigitado, senhaDigitada);
                if ("aluno".equals(tipo_usuario)) {
                    br.maua.domain.Aluno aluno = alunoDAO.obterAlunoCompleto(usuarioDigitado, senhaDigitada);
                    new br.maua.presentation.TelaTabuleiro.TelaTabuleiro1(aluno).setVisible(true);
                } else if ("professor".equals(tipo_usuario)) {
                    br.maua.domain.Professor professor = professorDAO.obterProfessorCompleto(usuarioDigitado, senhaDigitada);
                    new br.maua.presentation.TelaPainelDeControle.TelaPainelDeControle(professor).setVisible(true);
                } else {
                    new br.maua.presentation.TelaPainelDeControle.TelaPainelDeControle().setVisible(true);
                }
                this.dispose(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Usuário não encontrado ou senha incorreta!",
                    "Erro de Autenticação",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (java.sql.SQLException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this,
                "Erro ao conectar com o banco de dados: " + ex.getMessage(),
                "Erro de Conexão",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_entrarBotao10ActionPerformed

    private void entrarBotao11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarBotao11ActionPerformed
        // TODO add your handling code here:
        try {
            br.maua.presentation.TelaCadastroProfessor.TelaCadastroProfessor cadastro = new br.maua.presentation.TelaCadastroProfessor.TelaCadastroProfessor();
            cadastro.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao abrir tela de cadastro: " + e.getMessage());
        }
    }//GEN-LAST:event_entrarBotao11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastroTitulo5;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoUsername;
    private javax.swing.JButton entrarBotao10;
    private javax.swing.JButton entrarBotao11;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nomeTitulo10;
    private javax.swing.JPanel painelAzul;
    private javax.swing.JLabel senhaTitulo;
    // End of variables declaration//GEN-END:variables
}
