/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaEscolhaDeQuestionario;

/**
 *
 * @author Luiza
 */
public class TelaEscolhaDeQuestionario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEscolhaDeQuestionario.class.getName());

    /** Creates new form TelaPerfilAluno */
    public TelaEscolhaDeQuestionario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAzul = new javax.swing.JPanel();
        painelCinza = new javax.swing.JPanel();
        painelAzul1 = new javax.swing.JPanel();
        nomeTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAzul.setBackground(new java.awt.Color(19, 112, 178));

        painelCinza.setBackground(new java.awt.Color(217, 217, 217));
        painelCinza.setMaximumSize(new java.awt.Dimension(900, 600));
        painelCinza.setMinimumSize(new java.awt.Dimension(900, 600));
        painelCinza.setLayout(null);

        painelAzul1.setBackground(new java.awt.Color(19, 112, 178));
        painelAzul1.setMaximumSize(new java.awt.Dimension(710, 90));
        painelAzul1.setMinimumSize(new java.awt.Dimension(710, 90));
        painelAzul1.setName(""); // NOI18N
        painelAzul1.setPreferredSize(new java.awt.Dimension(710, 90));

        nomeTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        nomeTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo.setText("Tarefas");
        nomeTitulo.setName("nomeTitulo"); // NOI18N

        javax.swing.GroupLayout painelAzul1Layout = new javax.swing.GroupLayout(painelAzul1);
        painelAzul1.setLayout(painelAzul1Layout);
        painelAzul1Layout.setHorizontalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(nomeTitulo)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        painelAzul1Layout.setVerticalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeTitulo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        painelCinza.add(painelAzul1);
        painelAzul1.setBounds(94, 37, 720, 90);

        jButton1.setBackground(new java.awt.Color(240, 147, 23));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.setMaximumSize(new java.awt.Dimension(92, 33));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        painelCinza.add(jButton1);
        jButton1.setBounds(20, 10, 72, 23);

        javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
        painelAzul.setLayout(painelAzulLayout);
        painelAzulLayout.setHorizontalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAzulLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        painelAzulLayout.setVerticalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new br.maua.presentation.TelaTabuleiro.TelaTabuleiro1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEscolhaDeQuestionario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nomeTitulo;
    private javax.swing.JPanel painelAzul;
    private javax.swing.JPanel painelAzul1;
    private javax.swing.JPanel painelCinza;
    // End of variables declaration//GEN-END:variables

}
