/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package br.maua.presentation.TelaPainelDeControle;
import br.maua.domain.Professor;

/**
 *
 * @author Luiza
 */
public class TelaPainelDeControle extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPainelDeControle.class.getName());
    private final Professor professorLogado;


    public TelaPainelDeControle(Professor professor) {
        this.professorLogado = professor;
        initComponents();
        if (this.professorLogado != null) {
            nomeTitulo.setText("Bem vindo, " + this.professorLogado + "!");
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelAzul = new javax.swing.JPanel();
        painelCinza = new javax.swing.JPanel();
        botaoTabuleiro = new javax.swing.JButton();
        botaoAdmin = new javax.swing.JButton();
        painelAzul1 = new javax.swing.JPanel();
        nomeTitulo = new javax.swing.JLabel();
        fundoTabuleiro = new javax.swing.JLabel();
        fundoAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAzul.setBackground(new java.awt.Color(19, 112, 178));

        painelCinza.setBackground(new java.awt.Color(217, 217, 217));
        painelCinza.setMaximumSize(new java.awt.Dimension(900, 600));
        painelCinza.setMinimumSize(new java.awt.Dimension(900, 600));
        painelCinza.setLayout(null);

        botaoTabuleiro.setBackground(new java.awt.Color(153, 153, 153));
        botaoTabuleiro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        botaoTabuleiro.setText("Tabuleiro");
        botaoTabuleiro.setName("botaoTabuleiro"); // NOI18N
        botaoTabuleiro.addActionListener(this::botaoTabuleiroActionPerformed);
        painelCinza.add(botaoTabuleiro);
        botaoTabuleiro.setBounds(590, 450, 140, 32);
        botaoTabuleiro.getAccessibleContext().setAccessibleName("botaoTabuleiro");

        botaoAdmin.setBackground(new java.awt.Color(153, 153, 153));
        botaoAdmin.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        botaoAdmin.setText("Administração");
        botaoAdmin.setName("botaoAdmin"); // NOI18N
        botaoAdmin.addActionListener(this::botaoAdminActionPerformed);
        painelCinza.add(botaoAdmin);
        botaoAdmin.setBounds(569, 260, 160, 32);
        botaoAdmin.getAccessibleContext().setAccessibleName("botaoAdmin");

        painelAzul1.setBackground(new java.awt.Color(19, 112, 178));
        painelAzul1.setMaximumSize(new java.awt.Dimension(710, 90));
        painelAzul1.setMinimumSize(new java.awt.Dimension(710, 90));
        painelAzul1.setName(""); // NOI18N
        painelAzul1.setPreferredSize(new java.awt.Dimension(710, 90));

        nomeTitulo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 48)); // NOI18N
        nomeTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nomeTitulo.setText("Bem vindo, nomeProfessor!");
        nomeTitulo.setName("nomeTitulo"); // NOI18N

        javax.swing.GroupLayout painelAzul1Layout = new javax.swing.GroupLayout(painelAzul1);
        painelAzul1.setLayout(painelAzul1Layout);
        painelAzul1Layout.setHorizontalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAzul1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(nomeTitulo)
                .addGap(60, 60, 60))
        );
        painelAzul1Layout.setVerticalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeTitulo)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        painelCinza.add(painelAzul1);
        painelAzul1.setBounds(94, 37, 720, 90);

        fundoTabuleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Rectangle 31.png"))); // NOI18N
        fundoTabuleiro.setName("fundoTabuleiro"); // NOI18N
        painelCinza.add(fundoTabuleiro);
        fundoTabuleiro.setBounds(170, 340, 581, 175);
        fundoTabuleiro.getAccessibleContext().setAccessibleName("fundoTabuleiro");

        fundoAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/image fixed.png"))); // NOI18N
        fundoAdmin.setName("fundoAdmin"); // NOI18N
        painelCinza.add(fundoAdmin);
        fundoAdmin.setBounds(170, 150, 581, 175);
        fundoAdmin.getAccessibleContext().setAccessibleName("fundoAdmin");

        javax.swing.GroupLayout painelAzulLayout = new javax.swing.GroupLayout(painelAzul);
        painelAzul.setLayout(painelAzulLayout);
        painelAzulLayout.setHorizontalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAzulLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        painelAzulLayout.setVerticalGroup(
            painelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzulLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(painelCinza, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdminActionPerformed
        br.maua.presentation.TelaNavegacao.abrir(this, new br.maua.presentation.TelaPainelAdministrativo.TelaPainelAdministrativo1());
    }//GEN-LAST:event_botaoAdminActionPerformed

    private void botaoTabuleiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTabuleiroActionPerformed

        br.maua.presentation.TelaNavegacao.abrir(this, new br.maua.presentation.TelaTabuleiro.TelaTabuleiro1(this.professorLogado, true));
    }//GEN-LAST:event_botaoTabuleiroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdmin;
    private javax.swing.JButton botaoTabuleiro;
    private javax.swing.JLabel fundoAdmin;
    private javax.swing.JLabel fundoTabuleiro;
    private javax.swing.JLabel nomeTitulo;
    private javax.swing.JPanel painelAzul;
    private javax.swing.JPanel painelAzul1;
    private javax.swing.JPanel painelCinza;
    // End of variables declaration//GEN-END:variables

}
