/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaCorrecaoTarefa;

import br.maua.domain.*;
import br.maua.infrastructure.TentativaDAO;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Luiza
 */
public class TelaCorrecaoTarefa extends javax.swing.JFrame {

    private Tentativa tentativa;
    private final TentativaDAO tentativaDAO;
    private final List <JFormattedTextField> campoNotaUI = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCorrecaoTarefa.class.getName());

    /**
     * Creates new form TelaCorrecaoTarefa
     */
    public TelaCorrecaoTarefa(Tentativa tentativa) {
        this.tentativa = tentativa;
        initComponents();

        this.tentativaDAO = new TentativaDAO();
        carregarTentativa();

        jTextPane1.setEditable(false);
        jTextPane1.setFocusable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane6 = new javax.swing.JScrollPane();
        painelAzul1 = new javax.swing.JPanel();
        painelCinza1 = new javax.swing.JPanel();
        titulo3 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        painelQuestoes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelAzul1.setBackground(new java.awt.Color(19, 112, 178));

        painelCinza1.setBackground(new java.awt.Color(217, 217, 217));
        painelCinza1.setPreferredSize(new java.awt.Dimension(956, 725));

        titulo3.setBackground(new java.awt.Color(19, 112, 178));
        titulo3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 60)); // NOI18N
        titulo3.setForeground(new java.awt.Color(255, 255, 255));
        titulo3.setText("      Questionário");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(19, 112, 178));
        jTextPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane1.setText("Descrição da tarefa: \nQuestionário");
        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setBackground(new java.awt.Color(19, 112, 178));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SALVAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        painelQuestoes.setLayout(new javax.swing.BoxLayout(painelQuestoes, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane7.setViewportView(painelQuestoes);

        javax.swing.GroupLayout painelCinza1Layout = new javax.swing.GroupLayout(painelCinza1);
        painelCinza1.setLayout(painelCinza1Layout);
        painelCinza1Layout.setHorizontalGroup(
            painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titulo3, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(110, 110, 110))
        );
        painelCinza1Layout.setVerticalGroup(
            painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCinza1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCinza1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelAzul1Layout = new javax.swing.GroupLayout(painelAzul1);
        painelAzul1.setLayout(painelAzul1Layout);
        painelAzul1Layout.setHorizontalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(painelCinza1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        painelAzul1Layout.setVerticalGroup(
            painelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(painelCinza1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        for (int i = 0; i < tentativa.getRespostas().size(); i++) {

            Number numero = (Number) campoNotaUI.get(i).getValue();
            float notaDigitada = (numero != null) ? numero.floatValue() : 0.0f;
            tentativa.getRespostas().get(i).setNota(notaDigitada);

        }

        boolean confirmacaoCommit = tentativaDAO.atualizarNota(tentativa);

        if (confirmacaoCommit) {
            javax.swing.JOptionPane.showMessageDialog(this, "Notas salvas com sucesso!");
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar.");
        }
    }

    private void carregarTentativa(){

        this.tentativa = tentativaDAO.buscarTentativa(tentativa.getIdTentativa());
        popularTela();

    }

    private void popularTela() {

        painelQuestoes.removeAll();
        campoNotaUI.clear();

        int numeroQuestao = 1;

        for (Resposta resposta : tentativa.getRespostas()) {

            javax.swing.JPanel painelIndividual = new javax.swing.JPanel();
            painelIndividual.setLayout(new javax.swing.BoxLayout(painelIndividual, javax.swing.BoxLayout.Y_AXIS));
            painelIndividual.setBorder(javax.swing.BorderFactory.createTitledBorder("Questão " + numeroQuestao));
            javax.swing.JLabel labelEnunciado = new javax.swing.JLabel("Enunciado: " + resposta.getEnunciado());
            painelIndividual.add(labelEnunciado);
            painelIndividual.add(javax.swing.Box.createVerticalStrut(5));
            
            if (resposta instanceof RespostaDissertativa) {

                String respostaAluno = ((RespostaDissertativa) resposta).getRespostaAluno();
                javax.swing.JTextArea txtArea = new javax.swing.JTextArea(3, 40);
                txtArea.setText(respostaAluno != null ? respostaAluno : "O aluno não respondeu.");
                txtArea.setEditable(false);
                txtArea.setLineWrap(true);
                txtArea.setWrapStyleWord(true);
                painelIndividual.add(new javax.swing.JScrollPane(txtArea));

            }

            else if (resposta instanceof RespostaAlternativa) {

                RespostaAlternativa respostaAlternativa = (RespostaAlternativa) resposta;
                int idAlternativaAssinalada = respostaAlternativa.getIdAlternativaAssinalada();

                javax.swing.JPanel painelAlternativas = new javax.swing.JPanel();
                painelAlternativas.setLayout(new javax.swing.BoxLayout(painelAlternativas, javax.swing.BoxLayout.Y_AXIS));
                javax.swing.ButtonGroup alternativas = new javax.swing.ButtonGroup();

                if (respostaAlternativa.getQuestao() != null && respostaAlternativa.getQuestao().getAlternativas() != null) {
                    for (Alternativa alt : respostaAlternativa.getQuestao().getAlternativas()) {

                        javax.swing.JRadioButton radioBtn = new javax.swing.JRadioButton(alt.getEnunciado());
                        radioBtn.setEnabled(false);

                        if (alt.getIdAlternativa() == idAlternativaAssinalada) {
                            radioBtn.setSelected(true);
                        }

                        alternativas.add(radioBtn);
                        painelAlternativas.add(radioBtn);
                    }
                }
                painelIndividual.add(painelAlternativas);
            }

            else if (resposta instanceof RespostaUpload) {

                RespostaUpload respostaUpload = (RespostaUpload) resposta;
                String pathArquivo = respostaUpload.getPathArquivo();

                if (pathArquivo != null && !pathArquivo.trim().isEmpty()) {

                    javax.swing.JLabel labelUpload = new javax.swing.JLabel("Arquivo anexado: " + pathArquivo);
                    painelIndividual.add(labelUpload);
                    painelIndividual.add(javax.swing.Box.createVerticalStrut(5));

                    javax.swing.JButton buttonDownload = new javax.swing.JButton("Baixar Arquivo Submetido");
                    buttonDownload.addActionListener(new java.awt.event.ActionListener() {
                        @Override
                        public void actionPerformed(java.awt.event.ActionEvent e) {
                            try {

                                String pastaOrigem = "src/main/resources/assets/aluno/";
                                java.io.File arquivoOrigem = new java.io.File(pastaOrigem + pathArquivo);
                                String pastaDestino = "src/main/resources/assets/professor/";
                                java.io.File arquivoDestino = new java.io.File(pastaDestino + pathArquivo);
                                br.maua.service.ArquivoService.salvarArquivo(arquivoOrigem, arquivoDestino);

                                if (arquivoDestino.exists()) {
                                    java.awt.Desktop.getDesktop().open(arquivoDestino);
                                }

                                else {

                                    javax.swing.JOptionPane.showMessageDialog(TelaCorrecaoTarefa.this,
                                            "Arquivo não localizado em: " + arquivoDestino.getAbsolutePath(),
                                            "Arquivo não encontrado",
                                            javax.swing.JOptionPane.ERROR_MESSAGE);

                                }
                            }
                            catch (Exception ex) {

                                javax.swing.JOptionPane.showMessageDialog(TelaCorrecaoTarefa.this,
                                        "Erro ao tentar abrir o arquivo: " + ex.getMessage(),
                                        "Erro do Sistema",
                                        javax.swing.JOptionPane.ERROR_MESSAGE);

                            }
                        }
                    });
                    painelIndividual.add(buttonDownload);
                }

                else {
                    javax.swing.JLabel labelUpload = new javax.swing.JLabel("Nenhum arquivo foi anexado.");
                    painelIndividual.add(labelUpload);
                }
            }

            painelIndividual.add(javax.swing.Box.createVerticalStrut(8));
            javax.swing.JPanel painelNota = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
            painelNota.add(new javax.swing.JLabel("Nota: "));
            java.text.NumberFormat formatoDecimal = java.text.NumberFormat.getNumberInstance(java.util.Locale.US);
            formatoDecimal.setGroupingUsed(false);

            javax.swing.JFormattedTextField campoNotaQuestao = new javax.swing.JFormattedTextField(formatoDecimal);
            campoNotaQuestao.setColumns(5);
            campoNotaQuestao.setValue(resposta.getNota());

            painelNota.add(campoNotaQuestao);
            painelIndividual.add(painelNota);

            campoNotaUI.add(campoNotaQuestao);
            painelQuestoes.add(painelIndividual);
            painelQuestoes.add(javax.swing.Box.createVerticalStrut(15));

            numeroQuestao++;
        }

        painelQuestoes.revalidate();
        painelQuestoes.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        TelaCorrecaoTarefa tct = new TelaCorrecaoTarefa(new Tentativa(104));
        tct.setVisible(true);

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JPanel painelAzul1;
    private javax.swing.JPanel painelCinza1;
    private javax.swing.JPanel painelQuestoes;
    private java.awt.Label titulo3;
    // End of variables declaration//GEN-END:variables
}
