/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaAdicionarTurma;

import br.maua.domain.*;
import br.maua.enums.SemestreEnum;
import br.maua.infrastructure.DAO.*;

import javax.swing.*;
import java.sql.SQLException;
import java.util.List;
import java.util.Objects;

/**
 *
 * @author Lenovo
 */
public class TelaAdicionarTurma extends javax.swing.JFrame {
    private final JFrame anterior;
    /**
     * Creates new form TelaModalAdicionarTurma
     */
    public TelaAdicionarTurma(JFrame anterior) {
        this.anterior = anterior;
        initComponents();

        carregarComboAsync(comboBoxProfessor, ProfessorDAO::listarProfessores);
        carregarComboAsync(comboBoxCurso, CursoDAO::listarCursos);
        carregarComboAsync(comboBoxAno, AnoDAO::getAnos);
        carregarComboAsync(comboBoxTurma, TurmaDAO::listarTurmas);
        carregarComboAsync(comboBoxSubturma, SubturmaDAO::listarSubturmas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gapAno = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        comboBoxSemestre = new javax.swing.JComboBox<>();
        labelProfessor = new javax.swing.JLabel();
        comboBoxProfessor = new javax.swing.JComboBox<>();
        labelAno = new javax.swing.JLabel();
        comboBoxAno = new javax.swing.JComboBox<>();
        botaoAddAno = new javax.swing.JButton();
        labelCurso = new javax.swing.JLabel();
        comboBoxCurso = new javax.swing.JComboBox<>();
        botaoAddCurso = new javax.swing.JButton();
        labelTurma = new javax.swing.JLabel();
        comboBoxTurma = new javax.swing.JComboBox<>();
        botaoAddTurma = new javax.swing.JButton();
        labelSubturma = new javax.swing.JLabel();
        comboBoxSubturma = new javax.swing.JComboBox<>();
        botaoAddSubturma = new javax.swing.JButton();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gapAno.setBackground(new java.awt.Color(19, 112, 178));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Adicionar Turma");

        labelSemestre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSemestre.setForeground(new java.awt.Color(255, 255, 255));
        labelSemestre.setText("Semestre");

        comboBoxSemestre.setModel(getModelSemestre());

        labelProfessor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelProfessor.setForeground(new java.awt.Color(255, 255, 255));
        labelProfessor.setText("Professor");

        comboBoxProfessor.setModel(new DefaultComboBoxModel<>(new Professor[]{new Professor("Carregando...")}));

        labelAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelAno.setForeground(new java.awt.Color(255, 255, 255));
        labelAno.setText("Ano");

        comboBoxAno.setModel(new DefaultComboBoxModel<>(new Ano[]{new Ano(0)}));

        botaoAddAno.setText("+");
        botaoAddAno.addActionListener(this::botaoAddAnoActionPerformed);

        labelCurso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelCurso.setForeground(new java.awt.Color(255, 255, 255));
        labelCurso.setText("Curso");

        comboBoxCurso.setModel(new DefaultComboBoxModel<>(new Curso[]{new Curso("Carregando...")}));

        botaoAddCurso.setText("+");
        botaoAddCurso.addActionListener(this::botaoAddCursoActionPerformed);

        labelTurma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTurma.setForeground(new java.awt.Color(255, 255, 255));
        labelTurma.setText("Turma");

        comboBoxTurma.setModel(new DefaultComboBoxModel<>(new Turma[]{new Turma("Carregando...")}));

        botaoAddTurma.setText("+");
        botaoAddTurma.addActionListener(this::botaoAddTurmaActionPerformed);

        labelSubturma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelSubturma.setForeground(new java.awt.Color(255, 255, 255));
        labelSubturma.setText("Subturma");

        comboBoxSubturma.setModel(new DefaultComboBoxModel<>(new Subturma[]{new Subturma("Carregando...")}));

        botaoAddSubturma.setText("+");
        botaoAddSubturma.addActionListener(this::botaoAddSubturmaActionPerformed);

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(this::botaoSalvarActionPerformed);

        javax.swing.GroupLayout gapAnoLayout = new javax.swing.GroupLayout(gapAno);
        gapAno.setLayout(gapAnoLayout);
        gapAnoLayout.setHorizontalGroup(
            gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gapAnoLayout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gapAnoLayout.createSequentialGroup()
                        .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxSemestre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapAnoLayout.createSequentialGroup()
                                .addComponent(comboBoxTurma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAddTurma))
                            .addGroup(gapAnoLayout.createSequentialGroup()
                                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCurso)
                                    .addComponent(labelAno)
                                    .addComponent(labelTurma)
                                    .addComponent(labelSubturma))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(gapAnoLayout.createSequentialGroup()
                                .addComponent(comboBoxSubturma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAddSubturma))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapAnoLayout.createSequentialGroup()
                                .addComponent(comboBoxAno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAddAno))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gapAnoLayout.createSequentialGroup()
                                .addComponent(comboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAddCurso))
                            .addComponent(comboBoxProfessor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(205, 205, 205))
                    .addGroup(gapAnoLayout.createSequentialGroup()
                        .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSemestre)
                            .addComponent(labelProfessor))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(gapAnoLayout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(419, Short.MAX_VALUE))
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gapAnoLayout.setVerticalGroup(
            gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gapAnoLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(labelSemestre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAno)
                .addGap(7, 7, 7)
                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAddAno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddCurso)
                    .addComponent(comboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTurma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddTurma)
                    .addComponent(comboBoxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubturma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gapAnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAddSubturma)
                    .addComponent(comboBoxSubturma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(botaoSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gapAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gapAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private ComboBoxModel<SemestreEnum> getModelSemestre() {
        DefaultComboBoxModel<SemestreEnum> model = new DefaultComboBoxModel<>();
        for (SemestreEnum s : SemestreEnum.values()) {
            model.addElement(s);
        }
        return model;
    }

    private <T> void carregarComboAsync(
            JComboBox<T> comboBox,
            java.util.concurrent.Callable<List<T>> tarefa
    ) {
        comboBox.setEnabled(false);

        new SwingWorker<List<T>, Void>() {

            @Override
            protected List<T> doInBackground() throws Exception {
                return tarefa.call();
            }

            @Override
            protected void done() {
                try {
                    DefaultComboBoxModel<T> model = new DefaultComboBoxModel<>();

                    for (T item : get()) {
                        model.addElement(item);
                    }

                    comboBox.setModel(model);
                    comboBox.setEnabled(true);

                } catch (Exception e) {
                    comboBox.setEnabled(false);
                    comboBox.setModel(new DefaultComboBoxModel<>());
                }
            }
        }.execute();
    }

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            TurmaSubturmaDAO.commit(
                    (SemestreEnum) Objects.requireNonNull(comboBoxSemestre.getSelectedItem(), "Selecione o Semestre"),
                    (Professor) Objects.requireNonNull(comboBoxProfessor.getSelectedItem(), "Selecione o Professor"),
                    (Curso) Objects.requireNonNull(comboBoxCurso.getSelectedItem(), "Selecione o Curso"),
                    (Ano) Objects.requireNonNull(comboBoxAno.getSelectedItem(), "Selecione o Ano"),
                    (Turma) Objects.requireNonNull(comboBoxTurma.getSelectedItem(), "Selecione a Turma"),
                    (Subturma) Objects.requireNonNull(comboBoxSubturma.getSelectedItem(), "Selecione a Subturma")
        );
            JOptionPane.showMessageDialog(null, "Turma Salvo com sucesso!");
            dispose();
            anterior.setVisible(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar o turma");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoAddAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddAnoActionPerformed
        ModalAdicionarTurma modal = new ModalAdicionarTurma(
                this,
                "Adicionar Ano",
                "Digite o Ano",
                ano -> {
                    try {
                        AnoDAO.salvar(new Ano(Integer.parseInt(ano)));
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                });
        if (modal.isSalvo()) {
            carregarComboAsync(comboBoxAno, AnoDAO::getAnos);
        }
    }//GEN-LAST:event_botaoAddAnoActionPerformed

    private void botaoAddCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddCursoActionPerformed
        // TODO add your handling code here:
        ModalAdicionarTurma modal = new ModalAdicionarTurma(
                this,
                "Adicionar Curso",
                "Digite o Curso",
                curso -> {
                    try {
                        CursoDAO.salvar(new Curso(curso));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
        );
        if (modal.isSalvo()) {
            carregarComboAsync(comboBoxCurso, CursoDAO::listarCursos);
        }
    }//GEN-LAST:event_botaoAddCursoActionPerformed

    private void botaoAddTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddTurmaActionPerformed
        // TODO add your handling code here:
        ModalAdicionarTurma modal = new ModalAdicionarTurma(
                this,
                "Adicionar Turma",
                "Digite o Código da Turma (T00)",
                turma -> {
                    try {
                        TurmaDAO.salvar(new Turma(turma));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
        );
        if (modal.isSalvo()) {
            carregarComboAsync(comboBoxTurma, TurmaDAO::listarTurmas);
        }
    }//GEN-LAST:event_botaoAddTurmaActionPerformed

    private void botaoAddSubturmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddSubturmaActionPerformed
        // TODO add your handling code here:
        ModalAdicionarTurma modal = new ModalAdicionarTurma(
                this,
                "Adicionar Subturma",
                "Digite o Código da Subturma (SUB00)",
                subturma -> {
                    try {
                        SubturmaDAO.salvar(new Subturma(subturma));
                    } catch (SQLException e) {
                        throw new RuntimeException(e);
                    }
                }
        );
        if (modal.isSalvo()) {
            carregarComboAsync(comboBoxSubturma, SubturmaDAO::listarSubturmas);
        }
    }//GEN-LAST:event_botaoAddSubturmaActionPerformed

    public static void main(String[] args) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAdicionarTurma(new JFrame()).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddAno;
    private javax.swing.JButton botaoAddCurso;
    private javax.swing.JButton botaoAddSubturma;
    private javax.swing.JButton botaoAddTurma;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox<Ano> comboBoxAno;
    private javax.swing.JComboBox<Curso> comboBoxCurso;
    private javax.swing.JComboBox<Professor> comboBoxProfessor;
    private javax.swing.JComboBox<SemestreEnum> comboBoxSemestre;
    private javax.swing.JComboBox<Subturma> comboBoxSubturma;
    private javax.swing.JComboBox<Turma> comboBoxTurma;
    private javax.swing.JPanel gapAno;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelCurso;
    private javax.swing.JLabel labelProfessor;
    private javax.swing.JLabel labelSemestre;
    private javax.swing.JLabel labelSubturma;
    private javax.swing.JLabel labelTurma;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
