/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.maua.presentation.TelaAcoesTarefa;

import br.maua.presentation.TelaCriarTarefa.TelaCriarTarefa;

import javax.swing.*;

/**
 *
 * @author Luiza
 */
public class TelaAcoesTarefa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAcoesTarefa.class.getName());

    /**
     * Creates new form AcoesTarefa
     */
    public TelaAcoesTarefa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelAzul1 = new javax.swing.JPanel();
        btnCriarTarefas = new javax.swing.JButton();
        btnTarefasCriadas = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PainelAzul1.setBackground(new java.awt.Color(19, 112, 178));

        btnCriarTarefas.setBackground(new java.awt.Color(240, 147, 32));
        btnCriarTarefas.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnCriarTarefas.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarTarefas.setText("Criar Tarefa");
        btnCriarTarefas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCriarTarefas.addActionListener(this::btnCriarTarefasActionPerformed);

        btnTarefasCriadas.setBackground(new java.awt.Color(240, 147, 32));
        btnTarefasCriadas.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnTarefasCriadas.setForeground(new java.awt.Color(255, 255, 255));
        btnTarefasCriadas.setText("Tarefas Criadas");
        btnTarefasCriadas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTarefasCriadas.addActionListener(this::btnTarefasCriadasActionPerformed);

        Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 40)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Tarefas");
        Titulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PainelAzul1Layout = new javax.swing.GroupLayout(PainelAzul1);
        PainelAzul1.setLayout(PainelAzul1Layout);
        PainelAzul1Layout.setHorizontalGroup(
            PainelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAzul1Layout.createSequentialGroup()
                .addGroup(PainelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCriarTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PainelAzul1Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(btnTarefasCriadas, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PainelAzul1Layout.createSequentialGroup()
                            .addGap(423, 423, 423)
                            .addComponent(Titulo))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        PainelAzul1Layout.setVerticalGroup(
            PainelAzul1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAzul1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(btnCriarTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(btnTarefasCriadas, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelAzul1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTarefasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            TelaCriarTarefa cf = new TelaCriarTarefa(this);
            cf.pack();
            cf.setLocationRelativeTo(null);
            cf.setVisible(true);
        } catch (Exception e) {
            this.setVisible(true);
            JOptionPane.showMessageDialog(rootPane, "Erro ao criar Tarefa");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCriarTarefasActionPerformed

    private void btnTarefasCriadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarefasCriadasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        TelaTarefasCriadas ttc = new TelaTarefasCriadas();
        ttc.pack();
        ttc.setLocationRelativeTo(null);
        ttc.setVisible(true);
    }//GEN-LAST:event_btnTarefasCriadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAcoesTarefa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelAzul1;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton btnCriarTarefas;
    private javax.swing.JButton btnTarefasCriadas;
    // End of variables declaration//GEN-END:variables
}
